steps:
  # building the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-chat', '.']

  # pushing the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/user-chat']

  # Deploying container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['beta', 'run', 'deploy', 'user-chat', '--image', 'gcr.io/$PROJECT_ID/user-chat', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
